class AppStrings {
  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'PlaySpot',
      'home': 'Home',
      'map': 'Map',
      'events': 'Events',
      'ranks': 'Ranks',
      'host': 'Host',
      'profile': 'Profile',
      'games': 'Games',
      'events_title': 'Events',
      'leaderboard': 'Leaderboard',
      'no_events': 'No events yet',
      'create_event': 'Create one to get started!',
      'no_games': 'No games nearby',
      'join_game': 'Join Game',
      'game_full': 'Game Full',
      'loading': 'Loading...',
      'error': 'Error',
      'retry': 'Retry',
      'scan_qr': 'Scan QR Code',
      'host_dashboard': 'Host Dashboard',
      'share': 'Share',
      'filter_all': 'All',
      'filter_now': 'Now',
      'filter_today': 'Today',
      'filter_open': 'Open',
      'filter_nearby': 'Nearby',
    },
    'de': {
      'app_name': 'PlaySpot',
      'home': 'Startseite',
      'map': 'Karte',
      'events': 'Veranstaltungen',
      'ranks': 'Rangliste',
      'host': 'Veranstalten',
      'profile': 'Profil',
      'games': 'Spiele',
      'events_title': 'Veranstaltungen',
      'leaderboard': 'Rangliste',
      'no_events': 'Keine Veranstaltungen',
      'create_event': 'Erstelle eine!',
      'no_games': 'Keine Spiele in der Nähe',
      'join_game': 'Beitreten',
      'game_full': 'Spiel voll',
      'loading': 'Laden...',
      'error': 'Fehler',
      'retry': 'Wiederholen',
      'scan_qr': 'QR scannen',
      'host_dashboard': 'Host-Dashboard',
      'share': 'Teilen',
      'filter_all': 'Alle',
      'filter_now': 'Jetzt',
      'filter_today': 'Heute',
      'filter_open': 'Offen',
      'filter_nearby': 'In der Nähe',
    },
  };

  static String get(String key, [String language = 'en']) {
    return translations[language]?[key] ?? translations['en']?[key] ?? key;
  }
}
